// import { Inter } from 'next/font/google'
import { Playfair_Display } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

// const inter = Inter({ subsets: ['latin'] })

const playfair = Playfair_Display({ subsets: ['latin'], style: 'normal', weight: "400" })

export const metadata = {
  title: 'AI Powered Fraud Detection Software',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`playfair.className, bg-slate-200`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
